# Generated by Django 4.2.7 on 2025-11-17 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import voting.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Candidate name or option text",
                        max_length=100,
                        validators=[django.core.validators.MaxLengthValidator(100)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional candidate description",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Poll question or title",
                        max_length=200,
                        validators=[django.core.validators.MaxLengthValidator(200)],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional details about the poll",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether poll accepts new votes"
                    ),
                ),
                (
                    "max_votes",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum votes allowed (None = unlimited)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoterSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voter_fingerprint",
                    models.CharField(
                        help_text="Hash of voter IP + User-Agent", max_length=64
                    ),
                ),
                (
                    "cookie_token",
                    models.CharField(
                        default=voting.models.generate_token,
                        help_text="Unique token stored in voter's cookie",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="Voter's IP address"),
                ),
                ("user_agent", models.TextField(help_text="Browser User-Agent string")),
                ("first_visit", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "vote_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of votes from this session",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="Poll being accessed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voting.poll",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voter_fingerprint",
                    models.CharField(
                        help_text="Hash of voter IP + User-Agent to prevent duplicates",
                        max_length=64,
                    ),
                ),
                (
                    "ranking",
                    models.JSONField(
                        help_text="List of candidate UUIDs in ranked order [1st_choice, 2nd_choice, ...]"
                    ),
                ),
                ("cast_at", models.DateTimeField(auto_now_add=True)),
                (
                    "poll",
                    models.ForeignKey(
                        help_text="The poll this vote belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voting.poll",
                    ),
                ),
            ],
            options={
                "ordering": ["-cast_at"],
            },
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["-created_at"], name="voting_poll_created_e5ece2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["is_active"], name="voting_poll_is_acti_8bc28d_idx"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="poll",
            field=models.ForeignKey(
                help_text="The poll this candidate belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="voting.poll",
            ),
        ),
        migrations.AddIndex(
            model_name="votersession",
            index=models.Index(
                fields=["poll", "voter_fingerprint"],
                name="voting_vote_poll_id_9541af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="votersession",
            index=models.Index(
                fields=["cookie_token"], name="voting_vote_cookie__ac738f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="votersession",
            unique_together={("poll", "voter_fingerprint")},
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["poll", "voter_fingerprint"],
                name="voting_vote_poll_id_b26634_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vote",
            index=models.Index(
                fields=["-cast_at"], name="voting_vote_cast_at_5c5d8b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("poll", "voter_fingerprint")},
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["poll", "name"], name="voting_cand_poll_id_599e18_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidate",
            unique_together={("poll", "name")},
        ),
    ]
