# Generated by Django 4.2.7 on 2025-11-17 20:06

from django.db import migrations, models # pyright: ignore[reportMissingModuleSource, reportMissingImports]


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="creator_code",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique code to manage this poll as creator",
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft delete flag (poll hidden but not removed from DB)",
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Whether poll is visible on homepage"
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="tiebreaker_method",
            field=models.CharField(
                choices=[
                    ("schulze", "Schulze Method"),
                    ("borda", "Borda Count"),
                    ("random", "Random Selection"),
                ],
                default="schulze",
                help_text="Method for resolving Condorcet paradox",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["is_public"], name="voting_poll_is_publ_540af7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["is_deleted"], name="voting_poll_is_dele_e2acfb_idx"
            ),
        ),
    ]
