# Generated by Django 4.2.7 on 2025-11-22 12:07

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0003_add_results_released"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votersession",
            unique_together={("poll", "voter_fingerprint")},
        ),
        migrations.AlterField(
            model_name="votersession",
            name="cookie_token",
            field=models.CharField(
                db_index=True,
                default=voting.models.generate_token,
                help_text="Unique token stored in voter's cookie",
                max_length=64,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="votersession",
            unique_together={("poll", "voter_fingerprint"), ("poll", "cookie_token")},
        ),
    ]
