# Generated by Django 4.2.7 on 2026-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_update_site_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='allow_multiple_votes_per_device',
            field=models.BooleanField(default=False, help_text='If True, bypass cookie/fingerprint checks to allow multiple votes from same device'),
        ),
    ]
