# Generated by Django 4.2.7 on 2026-01-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0006_poll_allow_multiple_votes_per_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="requires_auth",
            field=models.BooleanField(
                default=False,
                help_text="Whether poll requires a unique one-time password to vote",
            ),
        ),
        migrations.CreateModel(
            name="PollToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_hash", models.CharField(max_length=128)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="voting.poll",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["poll", "token_hash"],
                        name="voting_poll_poll_id_4425ac_idx",
                    )
                ],
                "unique_together": {("poll", "token_hash")},
            },
        ),
    ]
