# Generated by Django 4.2.7 on 2026-01-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting", "0007_poll_requires_auth_polltoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="closing_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the poll will automatically close",
                null=True,
            ),
        ),
    ]
