# Generated by Django 5.2.12 on 2026-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0008_poll_closing_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="allow_vote_modification",
            field=models.BooleanField(
                default=False,
                help_text="Whether voters can modify their vote using a private management link",
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="management_token",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique token to view and manage this specific vote",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
