# Generated by Django 5.2.12 on 2026-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0009_poll_allow_vote_modification_vote_management_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="tiebreaker_method",
            field=models.CharField(
                choices=[
                    ("schulze", "Schulze"),
                    ("borda", "Borda Count"),
                    ("random", "Random Selection"),
                ],
                default="schulze",
                help_text="Method for resolving Condorcet paradox",
                max_length=20,
            ),
        ),
    ]
